### ISSUE TITLE
Failed to resolve: com.github.vilyever:AndroidSocketClient:1.2.1

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#1]
![qq 20160330145904](https://cloud.githubusercontent.com/assets/7868514/14134231/0d56f9d2-f688-11e5-84c4-6b0875000e2c.jpg)

看了下这个库，不错。

我在添加 gradle 依赖时出现上面错误，我的配置如下：
在 `project` 下的 gradle 脚本里添加：

```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        jcenter()
    }
}
```

在 `app` 的 gradle 脚本里添加依赖：

```
dependencies {
    compile 'com.github.vilyever:AndroidSocketClient:1.2.1'
}
```

哪里配置不对吗?

**Comment by vilyever** [comment]
貌似JitPack服务器抽风了 没生成成功，我处理一下

**Comment by vilyever** [comment]
1.2.2 版本测试可用了

**Comment by jp1017** [comment]
可以了，good job， 3ks
