### ISSUE TITLE
请问如何修改心跳包格式呢？

### ISSUE THREAD

**Issue by Lsy1992** [vilyever/AndroidSocketClient#10]
看到文档中只提到：socketClient.setHeartBeatInterval(1000 \* 30); // 设置心跳包发送间隔
那么如何自定义它的发送格式？因为有时候会根据服务端设置

**Comment by jp1017** [comment]
发送格式？

目前我所知这个库能发送字符串和字节数组

**Comment by Lsy1992** [comment]
可能是我的叙述表达上不太明确，我的意思是这样的： 假设现在服务器要求发送的心跳包为“@#@” 
那么我应该如何设定发送它？

**Comment by vilyever** [comment]
请查看 SocketClient.setHeartBeatMessage() 相关方法

**Comment by vilyever** [comment]
更新
socketClient.getHeartBeatHelper().setSendString("heart beat"); // 设置自动发送心跳包的字符串，若为null则不发送心跳包

**Comment by Lsy1992** [comment]
谢谢！
对了，这个库支持后台中实时获取Socket数据吗？
