### ISSUE TITLE
有处理粘包问题没

### ISSUE THREAD

**Issue by JackHuang-888** [vilyever/AndroidSocketClient#11]
有处理粘包问题没?

**Comment by vilyever** [comment]
socketClient.getSocketPacketHelper().setReceiveTailString("\r\n"); // 设置接收消息时判断消息结束的尾部信息，用于解决粘包分包问题，若为null则每次读取InputStream直到其为空，可能出现粘包问题

**Comment by bingely** [comment]
加进去，反而数据接收不到？啥原因
