### ISSUE TITLE
增加别名有什么好处呢？

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#12]
刚更新到1.5.1

发送字节数组可以有三个方法：

```
mSocketClient.sendBytes(mBytes);
mSocketClient.send(mBytes);
mSocketClient.sendData(mBytes);
```

看了下，都是调用 `sendData` 方法，这样有什么好处呢？

sendString 同样的东西。

个人感觉各一个就够了：

`sendString` 和 `sendBytes`

**Comment by jp1017** [comment]
方法有些太多了

http://blog.csdn.net/dd864140130/article/details/51475632

**Comment by vilyever** [comment]
因为之前写上去了 有项目用到，就不好直接删了，下次先 @deprecated 吧

**Comment by jp1017** [comment]
![1](https://cloud.githubusercontent.com/assets/7868514/15495839/047dd3ae-21c5-11e6-88f7-c5e46e3a2a71.jpg)

竟然有这个哥们 :smile:
