### ISSUE TITLE
心跳包不断变化问题

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#13]
现在我的问题是心跳包包含消息流水号，心跳包每次都是变化的

我现在的处理是每隔一段时间发送数据，把该数据作为心跳包

请问还有没有别的方式？

**Comment by vilyever** [comment]
我想这个需求不适合用在心跳包机制上。。 心跳包用于判断存活，不用于发送信息。

**Comment by jp1017** [comment]
嗯，对，心跳包用于判断存活，那么只好定时发送消息做为“心跳包”了

**Comment by vilyever** [comment]
增加了可变心跳包配置，可以试一下
