### ISSUE TITLE
有读写超时的判读和处理吗？

### ISSUE THREAD

**Issue by ghyzx** [vilyever/AndroidSocketClient#18]
比如数据发送时，对发送超时的判读和处理怎样做了？

**Comment by vilyever** [comment]
可以看首页的配置，超时自动断开

**Comment by ghyzx** [comment]
你说的是setRemoteNoReplyAliveTimeout吧，这个倒是有看到，这个是对整体的；
其实我是想说单次超时，比如一个数据包发送超时（网络不好或服务端故障等引起），可能要在SendThread的run函数里面catch Exception了吧

**Comment by vilyever** [comment]
超时是没有Exception的，发送的时候只有IOException，触发IOException就直接断开了，你对单次超时的发送包要做什么处理吗。

**Comment by ghyzx** [comment]
比如一个数据包发送超时 要重发，怎么处理好了？

**Comment by vilyever** [comment]
无法实现重发，超时基本就是表示tcp阻塞了，再发送也是无法写出数据到远程端的，这时候通常是断开重连再发送先前没发送失败的数据包。

**Comment by ghyzx** [comment]
好的，了解了，非常感谢！
