### ISSUE TITLE
读取汉字乱码的问题

### ISSUE THREAD

**Issue by venky321** [vilyever/AndroidSocketClient#19]
在SocketInputReader.java下，readBytes方法117行，list.add((byte) c)这行会导致汉字乱码，
应该替换成

```
if (!Character.isIdeographic(c)) {
 list.add((byte) c);
} else {
byte[] bytes = new String(new char[] { (char) c }).getBytes("UTF-8");
for (byte b : bytes) {
list.add(b);
 }
}
```

有其它更好的方式吗？

**Comment by vilyever** [comment]
一般发送汉字是会进行编码（比如UTF-8)转换byte数组，接收到byte数组后用相同编码转换成String即可，这块可以在SocketInputReader接收完成后整体进行，无需修改

**Comment by venky321** [comment]
这个我知道。问题是接收数据，使用readLine可以正常读取。但是使用readBytes时，接收到汉字的byte数组有缺失（英文和数字不受影响），接收完成后有缺失的byte数组无法正常转换成汉字。经过查找，list.add((byte) c)时需多转一次char解决问题，就是上面代码的意思。服务器环境用的netty框架，和其它Client通信正常。

**Comment by vilyever** [comment]
不明白”接收到汉字的byte数组有缺失“，是什么意思，既然能在add的list.add((byte) c)时转换解决，那么你在接收到整个包后再遍历转换也是一样的。
