### ISSUE TITLE
minSdk 16？

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#2]
![qq 20160330200902](https://cloud.githubusercontent.com/assets/7868514/14141729/776aa33e-f6b3-11e5-8c95-bf991b746ffb.jpg)

**Comment by vilyever** [comment]
4.1以下的用户太少了，没有做兼容测试，你要支持2.多的话可以直接clone导入或fork修改。

**Comment by jp1017** [comment]
是的，没这个需求。
之前老项目，无意发现而已
谢谢
