### ISSUE TITLE
3.0.0 设置固定发送心跳包。接收不到服务端发来的消息

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#21]
RT

```
    socketClient.getHeartBeatHelper().setDefaultSendData(HBBytes);//字节数组心跳包
    socketClient.getHeartBeatHelper().setHeartBeatInterval(5 * 1000); // 设置自动发送心跳包的间隔时长，单位毫秒
    socketClient.getHeartBeatHelper().setSendHeartBeatEnabled(true); // 设置允许自动发送心跳包，此值默认为false
```

2.0.3时，发送字符数组心跳包，正常接收

**Comment by vilyever** [comment]
是无法接收消息吗，收发应该是分开的呃，有没有设置其他地方。
socketClient.getSocketPacketHelper().setReadStrategy();
这个是一定要设置的，默认是手动读取消息，可以改成按包尾自动读取。

**Comment by jp1017** [comment]
@vilyever 能接收了，但是仍然有问题，就是 setReceiveTrailerData 后，会出现问题：https://github.com/vilyever/AndroidSocketClient/issues/22

**Comment by bingely** [comment]
“收发应该是分开”是什么意思，还是收不到消息
