### ISSUE TITLE
3.0.1 setReceiveTrailerData 后接收数据被截断

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#22]
```
setReceiveTrailerData(new byte[]{0x77})
```

这样，如果接收到的数据是[0x33, 0x77, 0x44, 0x55, 0x77]， 数据会被截断，导致出错

**Comment by vilyever** [comment]
这是正常现象啊，TrailerData肯定不能和正文内容冲突的，一般只有修改TrailerData或者换一个策略读取，所以我又做了那个按长度读取的策略。

**Comment by jp1017** [comment]
可以判断TrailerData的时候，确定是最后一个

**Comment by vilyever** [comment]
TrailerData的读取是：一直读取到和TrailerData相同的字节数组。
因为要避免粘包问题不能把buffer里面直接读完这样，所以没办法确定哪个字节是最后一个。
同时还有可能发送端把一段消息分成很多小段发送，用来显示发送进度这种。
所以就是考虑读取的时候buffer中的字节数是不确定的

**Comment by jp1017** [comment]
协议有规定，后面不能在加数据，前面是校验，也没法添加，先用之前2.0.1版本了 :cry:

**Comment by vilyever** [comment]
奇怪，2.0.1的读取包尾的算法好像是差不多的呃:cry:

**Comment by jp1017** [comment]
现在用2.0.1，然后变化的心跳包用handler定时发送搞定
