### ISSUE TITLE
一包的数据长度过大时会比较慢

### ISSUE THREAD

**Issue by Vikaso** [vilyever/AndroidSocketClient#26]
定义的是按长度自动接收，然后有一包的长度大概在10W左右，接收到数据的时候会延迟1-2S，现在用你要处理的数据要比较的即使，不知道能不能有办法解决

**Comment by Vikaso** [comment]
问题发现了 在你读取数据的时候使用的方法问题 我改了下的
  @Override
    public int read(char[] buffer, int offset, int count) throws IOException {
        throw new IOException("read() is not support for SocketInputReader, try readBytes().");
    }

```
public byte[] readToLength(int length) throws IOException {
    if (length <= 0) {
        return null;
    }

    synchronized (lock) {
        if (!__i__isOpen()) {
            throw new IOException("InputStreamReader is closed");
        }

        try {
            byte[] buffer = new byte[length];
            int index = 0;
            int c;
            int addin = 0;//已经读取的长度
            while (-1 != (c = this.inputStream.read())) {
```

//                        if (index < length) {
//
//                            buffer[index++] = (byte) c;
//                        }
//                        if (index >= length) {
//                            break;
//                        }
                    buffer[addin]= (byte) c;
                    Log.e("length",length+"");
                    index=this.inputStream.read(buffer,addin+1,length-1);
                    index+=1;
                    addin+=index;
                    Log.e("index",index+"");
                    length=length-index;
                    if (length<=0) {
                        break;
                    }
//                  }
                }
//                if (length!=index){
//                    return null;
//                }
                if (length!=0) {
                    return null;
                }

```
            return buffer;
        }
        catch (IOException e) {
            return null;
        }
    }
}
```

**Comment by vilyever** [comment]
不好意思，最近在忙着面试，电脑也出了点问题，今天刚刚把这个弄好@.@
