### ISSUE TITLE
怎么设置为『收到什么就立刻返回什么』的模式？

### ISSUE THREAD

**Issue by Summer006** [vilyever/AndroidSocketClient#29]
这个库功能有点复杂，现在卡在ReadStrategy了，我需要的很简单，就是收到什么就返回什么，收到多少就立刻返回多少，不需要包头包尾包长之类的。找了半天似乎没发现有这个模式，除了自己改以外，有没有简单的方法？谢谢！

**Comment by vilyever** [comment]
一般是依据长度信息或者固定包尾截取信息，不按每次发送多少接收多少，可查询socket粘包问题。

**Comment by Summer006** [comment]
谢谢，我已自己改好。
粘包问题问题，我是在上层自己解决的。

btw：
顺便提一下，可以改进的地方：
disconnect回调希望可以加上一个exception或其他类型的参数，表示什么原因disconnect： 对方主动断开or网络异常断开or超时断开or主动断开？

**Comment by vilyever** [comment]
嗯，解决就好。
有时间会改进一下，最近工作有点忙@.@
