### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#3]
刚使用了下，遇到个问题：
`SocketClient` 的构造方法

```
public SocketClient(@NonNull String remoteIP, int remotePort) {
        this(remoteIP, remotePort, DefaultConnectionTimeout);
    }
```

里面的第一个参数是客户端的 ip ？我现在是用一个调试工具，建了个 socket 服务端：

![qq 20160331105631](https://cloud.githubusercontent.com/assets/7868514/14164136/36a7ff96-f72f-11e5-94e0-25f7e6705362.jpg)
需要和这个服务端通信，该如何处理呢？

我如下使用

```
mSocketClient = new SocketClient("192.168.1.108", 60000);
mSocketClient.connect();
```

结果是未连接，该如何操作呢？

**Comment by vilyever** [comment]
关闭防火墙试试，可能双方ping不通。
然后向android端发送数据时，每条数据末尾要加换行符（ ‘\n’ 或 '\r\n' ），你这个工具好像不支持发送换行符。

**Comment by jp1017** [comment]
我这是修改别的项目，原项目是可以正常连接，发送，接收，关闭，重连的。

别的项目：https://github.com/jp1017/android-socket-client

现在的问题是用力这个库连接不上，，，

```
mSocketClient.connect();
```

运行后：

打印

```
Log.i("tagtag", "isconnect: " + mSocketClient.isConnected());
```

结果为 `false`

**Comment by vilyever** [comment]
![2016-03-31_114657](https://cloud.githubusercontent.com/assets/5266554/14164925/7d8ae1a6-f736-11e5-8c51-805a56090d93.png)
![2016-03-31_114734](https://cloud.githubusercontent.com/assets/5266554/14164926/7ed34a4e-f736-11e5-8c95-44d7f3a36c90.png)
![2016-03-31_114721](https://cloud.githubusercontent.com/assets/5266554/14164927/80c35894-f736-11e5-83f8-6b4b78165f6e.png)

测试了一下，连接是没问题，不清楚你那边具体的问题。

**Comment by jp1017** [comment]
刚才估计出毛病，现在好了，什么都没改，服了

3ks

**Comment by bingely** [comment]
为啥监听不到消息呢
