### ISSUE TITLE
数据编码问题

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#5]
我注意到，该库发送和接收都是 utf-8 编码，我们的数据需要 gbk 编码

问题是：发送和接收的时候，可否指定编码格式？:laughing: :laughing:

**Comment by vilyever** [comment]
之后有空会添加这个功能，暂时你可以通过getBytes()后new String()来实现。

**Comment by vilyever** [comment]
新版本已发布，修改了消息收发机制，监听回调数据类型有所修改，可以在项目首页查看一些具体示例。

**Comment by jp1017** [comment]
看到了，超级棒！
:+1:

**Comment by jp1017** [comment]
刚看了下，这个库的 star 飞速增加，哈哈，gank 大法好
:smile:

**Comment by vilyever** [comment]
什么情况这是，九脸茫然中。

**Comment by jp1017** [comment]
:smile: 哈哈哈，在 http://gank.io/ 上给你推了推，好东西传播的快，看好你哦 :smile:

**Comment by vilyever** [comment]
thx，也感谢你很多建议☺

**Comment by vilyever** [comment]
emoji怎么发不了😳

**Comment by jp1017** [comment]
:bookmark: https://github.com/vilyever/AndroidSocketClient/issues/6
