### ISSUE TITLE
Builder 设计模式

### ISSUE THREAD

**Issue by jp1017** [vilyever/AndroidSocketClient#6]
:+1: 
另外，刚看了一个博客，说到：

> 当实例化一个类时有很多可选参数的时候,我们或许会写很多不同参数的构造方法,可读性会非常差,并且客户端也不知道在什么时候用什么构造器,这是非常非常糟糕的,同样静态方工厂也不能避免,这个时候我们需要用到构建器,也即设计模式里的Builder模式

我注意到你最新的1.3.3里面的 SocketPacket 类有很多构造方法，并且也遇到可读性差问题，是否可以考虑下 Builder 设计模式。
:100:

**Comment by vilyever** [comment]
后续有时间可能会更改一下，不过这块暂时由于SocketPacket的构造是由SocketClient内部实现的，就是暂时还没有发送SocketPacket的接口，所以可能必要性不是很大。
