### ISSUE TITLE
没有重连机制吗

### ISSUE THREAD

**Issue by hoffergg** [vilyever/AndroidSocketClient#7]
没有重连机制吗

**Comment by vilyever** [comment]
没有自动重连，之前考虑到断开的原因有很多，如果目标主机更换了ip端口，可能会不断重连，还是建议在onDisconnected回调中手动处理，后续如果考虑好的话会加入这个功能。

**Comment by hoffergg** [comment]
有没有其他成熟的android socket框架推荐呢？

**Comment by jp1017** [comment]
@vilyever 我在onDisconnected回调里，直接socketClient.connect();有时连上，有时连不上，还需要别的操作？

**Comment by vilyever** [comment]
我在demo上测试没发现问题呃，你要不要看下demo和你的代码又没什么区别
