### ISSUE TITLE
真机链接不上

### ISSUE THREAD

**Issue by CHparis** [vilyever/AndroidSocketClient#9]
我这边真机一连上就断开链接，然后我在断开链接里面重复去去链接，循环几次之后，会连上，然后，一发送数据，又直接断开链接，请问出现这种情况的原因有哪些呢？真机确实有网。

**Comment by vilyever** [comment]
可否clone或下载这个项目在AndroidStudio直接运行，默认有一个本机自己连接自己的demo，尝试一下是否有问题。

**Comment by CHparis** [comment]
运行起来了，是可以正常运行的，正常连接的。但是连这个服务器的时候就直接断开了，"123.59.11.73":" 800"。

**Comment by vilyever** [comment]
可以的话尝试一下两台安卓设备使用这个库互相连接，看看是否是由于服务器的原因导致的，我这边马上放假了，手头没有电脑测试 orz。

**Comment by CHparis** [comment]
恩，服务器应该是没有问题，我用iOS连上是可以的，用原生Socket也是可以直接连上的。节日快乐。

**Comment by jp1017** [comment]
没遇到过这问题，节日快乐。
:+1: :sunrise_over_mountains:
